### ISSUE TITLE
redux store is not connecting to navbar component

### ISSUE THREAD

**Issue by tortei1000** [gygtyme/gig-time#28]
The redux store is not connected to the navbar component.  When console.log the props that should be coming back from redux are undefined.  We are checking to see if it is a problem on the component or on the redux reducer.

**Comment by jankney2** [comment]
I helped tiago out with this one- refer to https://react-redux.js.org/introduction/quick-start 

refer to the code snippet under the connect() section for the answer- the issue is that we were not returning a value from our mapStateToProps function. you can declare any props (the example uses state.counter) that you'll be able to access.
